const test=require('node:test'),assert=require('node:assert/strict');
let create;test.before(async()=>{create=(await import('../supabase/functions/clever-processor/handler.mjs')).createCleverProcessor;});
const env=k=>({SUPABASE_URL:'https://project.test',SUPABASE_ANON_KEY:'public-test',GEMINI_API_KEY:'server-secret-for-test'}[k]||'');
const good={candidates:[{finishReason:'STOP',content:{parts:[{text:'S: Dados revisados.\nO: Não avaliado.\nA: Registro.\nP: Revisar.'}]}}]};
const request=(body,headers={})=>new Request('https://function.test',{method:'POST',headers:{Authorization:'Bearer synthetic',Origin:'https://esf2.vercel.app','Content-Type':'application/json',...headers},body:typeof body==='string'?body:JSON.stringify(body||{tipoAcao:'gerar_soap',tipoConsulta:'consulta_enfermagem',dadosConsulta:{soapLocal:'S: Informado. O: Não avaliado. A: Acompanhamento. P: Proposta de revisão.'}})});
function mock(changes={}){const calls=[];return{calls,fetchImpl:async(url,options)=>{calls.push({url,options});let data=url.includes('/auth/v1/')?{id:'user-a'}:url.includes('/perfis?')?[{permissoes:{usar_ia_soap:true}}]:url.includes('/rpc/')?true:good;const route=url.includes('generativelanguage')?'gemini':url.includes('/auth/v1/')?'auth':url.includes('/perfis?')?'profile':'quota';if(changes[route])return changes[route](url,options);return new Response(JSON.stringify(data),{status:200});}};}
test('Gemini: CORS permitido e autenticação obrigatória antes do provedor',async()=>{const m=mock(),h=create({env,...m});assert.equal((await h(new Request('https://function.test',{method:'OPTIONS',headers:{Origin:'https://esf2.vercel.app'}}))).status,204);assert.equal((await h(request(undefined,{Authorization:''}))).status,401);assert.equal((await h(request(undefined,{Origin:'https://evil.test'}))).status,403);assert.equal(m.calls.length,0);});
test('Gemini: usuário sem permissão não consome cota nem IA',async()=>{const m=mock({profile:async()=>new Response(JSON.stringify([{permissoes:{usar_ia_soap:false}}]))});assert.equal((await create({env,...m})(request())).status,403);assert.equal(m.calls.length,2);});
test('Gemini: JSON inválido, texto ausente e corpo grande têm erros reais',async()=>{const m=mock(),h=create({env,...m});assert.equal((await h(request('{'))).status,400);assert.equal((await h(request({tipoAcao:'gerar_soap'}))).status,400);assert.equal((await h(request('x'.repeat(33000)))).status,413);assert.ok(!m.calls.some(x=>x.url.includes('generativelanguage')));});
test('Gemini: segredo ausente e cota não instalada impedem geração',async()=>{let h=create({env:k=>k==='GEMINI_API_KEY'?'':env(k),...mock()});let r=await h(request());assert.equal(r.status,503);assert.equal((await r.json()).codigo,'GEMINI_NOT_CONFIGURED');const m=mock({quota:async()=>new Response('{}',{status:404})});r=await create({env,...m})(request());assert.equal(r.status,503);assert.equal((await r.json()).codigo,'QUOTA_NOT_READY');assert.ok(!m.calls.some(x=>x.url.includes('generativelanguage')));});
test('Gemini: cota excedida e falha do provedor não retornam sucesso',async()=>{for(const [fixture,status]of [[{quota:async()=>new Response('false')},429],[{gemini:async()=>new Response('{}',{status:429})},429],[{gemini:async()=>new Response('{}',{status:400})},502]]){const r=await create({env,...mock(fixture)})(request());assert.equal(r.status,status);const data=await r.json();assert.equal(data.bloqueado,true);assert.ok(data.codigo);}});
test('Gemini: espera e leitura de resposta têm limite; a chamada é abortada',async()=>{let aborted=false;const m=mock({gemini:async(url,options)=>{options.signal.addEventListener('abort',()=>aborted=true);return {ok:true,status:200,json:()=>new Promise(()=>{})};}});const r=await create({env,...m,timeoutMs:15})(request());assert.equal(r.status,504);assert.equal((await r.json()).codigo,'GEMINI_TIMEOUT');assert.ok(aborted);});
test('Gemini: resposta vazia, pensamento isolado e texto truncado são recusados',async()=>{for(const data of [{},{candidates:[{finishReason:'STOP',content:{parts:[{thought:true,text:'pensamento interno'}]}}]},{candidates:[{finishReason:'MAX_TOKENS',content:{parts:[{text:'incompleto'}]}}]}]){const r=await create({env,...mock({gemini:async()=>new Response(JSON.stringify(data))})})(request());assert.equal(r.status,502);}});
test('Gemini: produção não fica em modo teste e chave não vai na URL/resposta',async()=>{const m=mock(),r=await create({env,...m})(request()),data=await r.json();assert.equal(r.status,200);assert.equal(data.data.modoTeste,false);assert.ok(!data.data.soap.includes('RASCUNHO'));const sent=m.calls.find(x=>x.url.includes('generativelanguage'));assert.ok(!sent.url.includes('server-secret'));assert.equal(sent.options.headers['x-goog-api-key'],'server-secret-for-test');assert.ok(!JSON.stringify(data).includes('server-secret'));assert.equal(r.headers.get('Cache-Control'),'no-store');});
test('Gemini: teste usa só o exemplo do servidor e ignora instrução/modelo do cliente',async()=>{const m=mock(),r=await create({env,...m})(request({tipoAcao:'testar_conexao',model:'malicious',perfilUsuario:'admin',dadosConsulta:{soapLocal:'IDENTIFICADOR QUE NAO DEVE SAIR'}})),data=await r.json();assert.equal(data.data.modoTeste,true);const sent=m.calls.find(x=>x.url.includes('generativelanguage'));assert.ok(sent.url.includes('gemini-2.5-flash'));assert.ok(!sent.options.body.includes('IDENTIFICADOR'));assert.ok(!sent.options.body.includes('malicious'));});
test('Gemini: arquivo único compila, registra função e mantém autenticação',async()=>{const vm=require('node:vm'),{build}=require('../scripts/build-gemini-function.cjs');let handler;const context={Deno:{env:{get:()=>''},serve:fn=>handler=fn},Request,Response,AbortController,TextDecoder,setTimeout,clearTimeout,crypto,fetch:async()=>{throw Error('Rede não autorizada no teste');},console:{info:()=>{}}};vm.runInNewContext(build(),context);assert.equal(typeof handler,'function');assert.equal((await handler(request(undefined,{Authorization:''}))).status,401);assert.equal((await handler(new Request('https://function.test',{method:'OPTIONS',headers:{Origin:'https://esf2.vercel.app'}}))).status,204);});
